同时对动态属性相关类型与World类型进行了翻译
XeroAlpha/sapi-typedoc pull request #3
Opened 2023-01-19 04:54 UTC by Silvigarabis

部分与动态属性相关的类型已翻译完毕，同时世界类型也完成了翻译。
部分条目仍未进行完成测试，且由于精力不足，某些内容没有经过任何测试，这些内容以“需要更多测试”或“需要验证”标出。
并且，对于 `World.getTime()`，`World.getAbsoluteTime()` 与 `World.setTime()` 的作用，我没有能够进行准确的描述，如果有更好的翻译，请向我提出。
某些条目的描述略显繁琐，如果可能的话，可以想办法将他们变得简练（可惜我没想到）。

2023-01-19 05:04 UTC, Silvigarabis commented
- `World.getTime()` 返回的结果与命令 `/time query daytime` 相同  
- `World.getAbsoluteTime()` 返回的结果有点复杂，是命令 `/time query day` 的结果乘上 `24000` 加上命令 `/time query daytime` 的结果。  
- `World.setTime()` 尚未进行测试……

2023-01-19 08:57 UTC, XeroAlpha requested changes

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> + * 此类型用于定义一系列动态属性。能够与 {@link PropertyRegistry} 结合使用，在实体或世界上定义动态属性。一个 {@link PropertyRegistry} 可从 {@link WorldInitializeEvent.propertyRegistry} 获取。
“一个 {@link PropertyRegistry}”改成“{@link PropertyRegistry} 对象”或者“{@link PropertyRegistry} 实例”更为合适。

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 增加一个布尔类型的动态属性定义。
定义本身就是名词，在上方的类的描述中也同样使用了其名词的用法。
```
定义一个布尔型动态属性。
```
下同。

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
>       * @param identifier
未翻译描述与参数。

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 为实体类型注册动态属性（例如：`minecraft:skeleton`）。
实体类型需要定语“特定”、“指定”或者参数名。
```
为特定实体类型注册动态属性。
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 设 “属性的标识符编码为 UTF-8 后的字节长度” 为 `a`，则允许的最大长度 `b = 998 - a`。若尝试为实体类型 `entityType` 注册字符串类型的动态属性，且属性的值最大长度大于 `b`，计算 `totalMaxLength = a + b + 2`，抛出 `"Dynamic property size limit exceeded (<totalMaxL
这个错误是单个属性的大小超过限制，可以将属性大小的计算方式放在 `DynamicPropertiesDefinition` 的描述中。在 `throws` 块中只需要说明大小超过限制即可。
下同。

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> + * 代表了整个世界的类型，其中包含了一系列维度以及 Minecraft 的环境。
不推荐用“代表”一词。
```
表示一个世界。包含了世界的各种状态，即一系列维度以及 Minecraft 的环境。
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * @returns 返回的数组中包含代表了游戏中每个玩家的对象。
`returns` 块后面跟随的应当是一个名词。
```
@returns 由世界中所有在线玩家所组成的数组。
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * @returns 与 `dimensionId` 关联的维度对象。
英文不应移除。
```
@returns
与 `dimensionId` 关联的维度对象。

The requested dimension
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 若 `dimensionId` 不与维度关联，抛出 `"Dimension '<dimensionId>' is invalid"`。
`throws` 块中只有 `This function can throw errors.` 等少数情况可不保留英文原句，其他情况需要保留英文。
```md
@throws
若 `dimensionId` 不与维度关联，抛出 `"Dimension '<dimensionId>' is invalid"`。

Throws if the given dimension name is invalid
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * @param options 可选的参数，用作于筛选指定条件的玩家。
多行块需要换行
```
@param options
可选的……
注意，……
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * @returns 一个能够获取到世界中所有玩家的可迭代对象。
同上，需要换行并保留英文原文。此外返回的是可迭代的迭代器（`IterableIterator`）。

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 获得一天里的当前时间。
time of the day 作为一个词组“一天中的时间”不应拆分。
```
返回当前一天中的时间（自午夜开始的游戏刻）。
```

2023-01-19 08:57 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 设置一天的当前时间（需要验证）。
问题同 `getTime`。

2023-01-19 12:18 UTC, Silvigarabis commented on translated/server.d.ts
> +     * 增加一个布尔类型的动态属性定义。
然而实际上未定义任何东西，所有将要定义的动态属性都被存储在创建的`DynamicPropertiesDefinition`对象中，直到使用`PropertyRegistry`的方法进行注册。
如果此处直接使用“定义属性”的确比“增加属性定义”要好，我会使用它，不过我现在不确定。
也可能是我对“属性”，“定义”，与“注册”不太了解。
不管如何，修改此处可能需要更多的讨论。

2023-01-19 12:20 UTC, Silvigarabis commented on translated/server.d.ts
> +     * 获得一天里的当前时间。
同意，但是它不是从午夜开始计算的

2023-01-19 12:33 UTC, Silvigarabis commented on translated/server.d.ts
> +     * 设 “属性的标识符编码为 UTF-8 后的字节长度” 为 `a`，则允许的最大长度 `b = 998 - a`。若尝试为实体类型 `entityType` 注册字符串类型的动态属性，且属性的值最大长度大于 `b`，计算 `totalMaxLength = a + b + 2`，抛出 `"Dynamic property size limit exceeded (<totalMaxL
这样应该可以，但是是“‘值最大长度’超限”还是“‘最大长度’超限”呢？这点我难以决定。如果没有更好的描述，我会使用“当属性大小超出限制”

2023-01-19 13:07 UTC, Silvigarabis commented on translated/server.d.ts
> +     * @returns 返回的数组中包含代表了游戏中每个玩家的对象。
已修改，但可能较为繁杂，此处列出了修改后的句子，同时列出分词后的句子
`返回一个包含着游戏中所有玩家的对象的数组`
`返回一个 包含着 游戏中 所有玩家的 对象 的数组`
这需要考虑一下怎么遣词造句。我想不到……

2023-01-19 13:22 UTC, Silvigarabis commented on translated/server.d.ts
> +     * 设置一天的当前时间（需要验证）。
此处将会恢复为未翻译状态，由于正在对此方法进行测试

2023-01-19 13:39 UTC, Silvigarabis commented
等待讨论完成中……

2023-01-19 13:40 UTC, Silvigarabis commented on translated/server.d.ts
> +     * 获得一天里的当前时间。
是否应当补充更多说明？

2023-01-21 04:15 UTC, Silvigarabis commented on translated/server.d.ts
> +     * 增加一个布尔类型的动态属性定义。
此处将会使用“定义属性”的描述

2023-01-21 04:17 UTC, Silvigarabis commented on translated/server.d.ts
> + * 代表了整个世界的类型，其中包含了一系列维度以及 Minecraft 的环境。
虽然我觉得可能更适合“代表”，但此处仍然使用“表示”

2023-01-21 06:45 UTC, merged