Update server.d.ts
XeroAlpha/sapi-typedoc pull request #4
Opened 2023-01-21 11:22 UTC by kkj9333

翻译了EntityInventoryComponent

2023-01-21 12:12 UTC, XeroAlpha requested changes
请先阅读 [翻译规则](https://github.com/XeroAlpha/sapi-typedoc/tree/main/translated#%E7%BF%BB%E8%AF%91%E8%A7%84%E5%88%99) 再进行翻译。

2023-01-21 12:54 UTC, kkj9333 commented
> 请先阅读 [翻译规则](https://github.com/XeroAlpha/sapi-typedoc/tree/main/translated#%E7%BF%BB%E8%AF%91%E8%A7%84%E5%88%99) 再进行翻译。
按照#2 进行了翻译，移除了异常抛出

2023-01-21 15:02 UTC, XeroAlpha requested changes

2023-01-21 15:02 UTC, XeroAlpha commented on translated/server.d.ts
> + * 定义一个实体的物品栏属性
块中的文本都是完整的句子。都需要以句号或者其他标点符号作为结尾。

2023-01-21 15:02 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 若为true, 则表示实体物品栏的物品可以被转移走，比如漏斗
包含代码的部分需要使用反引号括起。

2023-01-21 15:02 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 定义实体的容器
这是一个属性，用于获得对应实体的物品栏组件的容器对象，不应使用“定义”这个动词。
```
表示实体的容器。
```

2023-01-21 15:33 UTC, kkj9333 commented on translated/server.d.ts
> + * 定义一个实体的物品栏属性
> 块中的文本都是完整的句子。都需要以句号或者其他标点符号作为结尾。

明白，辛苦了，明天整改，祝除夕快乐！

2023-01-22 12:39 UTC, XeroAlpha approved these changes

2023-01-23 07:44 UTC, merged