增加了minecraft-server中方块组件类型的翻译
XeroAlpha/sapi-typedoc pull request #5
Opened 2023-01-22 01:53 UTC by PrairieFire2b

方块组件类型的大部分内容已翻译完毕，但是由于精力和时间问题，暂未经测试，更多内容会在下面几次上传中补充。

2023-01-22 04:41 UTC, PrairieFire2b commented
部分函数需要在beta版本中进行测试，先把今天的上传了。改正了一些有语病的句子，增添了容器类的翻译。

2023-01-22 08:10 UTC, XeroAlpha requested changes

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
> + * 表示方块物品栏组件。在某些方块上可以被使用，如箱子。
后面一句可以改成
```
可以在箱子等方块上使用。
```

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 该方块的源位置。
歧义。这个 `location` 是组件所属方块的位置，还是熔岩源方块的位置？

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
> + * 表示方块的活塞组件。当出现在方块上，该方块具有类似于活塞的行为。
```
表示方块的活塞组件。当出现在方块上，该方块会表现出类似于活塞的行为。
```

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 该方块的源位置。
我看了下这个好像是炼药锅的组件，第一时间没反应过来。

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
> +     * ( 若希望把物品放置在特定槽位，使用 `setItem` 方法。)
中文段落中的括号应当使用中文括号。
```
（若希望把物品放置在特定槽位，使用 {@link setItem} 方法。）
```

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
>       * @param slot
有一点需要注意：有两种方式可以指定一个槽位，第一种是 `ContainerSlot` 对象，第二种是 `slot` 数字参数。

为了区分两种不同的表示方式，在此将前一种表示方式称为“槽位”，而后一种表示方式称为“槽位编号”。详见 [命令/item](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/item)
```
@param slot 指定的槽位编号。
```

2023-01-22 08:10 UTC, XeroAlpha commented on translated/server.d.ts
>       * @param fromSlot
```
@param fromSlot 物品原本所在的槽位编号。
```

2023-01-22 08:17 UTC, XeroAlpha commented on translated/server.d.ts
> +     * 表示容器内空置槽位的数量。
可以使用 inheritDoc 特殊规则了。详见 [translated/README.md#L60](https://github.com/XeroAlpha/sapi-typedoc/blob/main/translated/README.md?plain=1#L60)

2023-01-22 15:04 UTC, PrairieFire2b commented on translated/server.d.ts
> +     * 该方块的源位置。
是组件所属方块的位置。修改为“该方块的位置”是否会更合理？源貌似是一个多余的形容词。

2023-09-27 08:39 UTC, XeroAlpha commented
请将翻译迁移至 `translate-pieces` 文件夹

2023-09-27 08:39 UTC, closed without merging